[env:binary_watch]
platform          = ststm32
board             = nucleo_l031k6
framework         = hal
board_build.mcu   = stm32l031d6px
board_build.f_cpu = 16000000L
upload_protocol   = stlink
debug_tool        = stlink
build_flags =
    -DSTM32L031xx
    -DUSE_HAL_DRIVER
