[env:binary_watch]
platform          = ststm32
board             = genericSTM32L031F6
framework         = hal
board_build.mcu   = stm32l031f6p6
board_build.f_cpu = 16000000L
upload_protocol   = stlink
debug_tool        = stlink
build_flags =
    -DSTM32L031xx
    -DUSE_HAL_DRIVER
